// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function TaskInput(props) {
  var addTask = props.addTask;
  var match = React.useState(function () {
        return "";
      });
  var setTitle = match[1];
  var title = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setDescription = match$1[1];
  var description = match$1[0];
  var handleSubmit = function () {
    if (title !== "" && description !== "") {
      addTask(title, description);
      setTitle(function (param) {
            return "";
          });
      return setDescription(function (param) {
                  return "";
                });
    }
    
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Gestionnaire de tâches minimaliste",
                      className: "font-bold mb-2",
                      style: {
                        fontFamily: "Times New Roman",
                        fontSize: "15px"
                      }
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Liste de Tâches",
                      className: "text-xl mb-4",
                      style: {
                        fontSize: "13px"
                      }
                    }),
                JsxRuntime.jsxs("form", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("label", {
                                      children: "Title:",
                                      className: "text-sm mb-1"
                                    }),
                                JsxRuntime.jsx("input", {
                                      className: "border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500",
                                      placeholder: "What's the title of your To Do?",
                                      value: title,
                                      onChange: (function (e) {
                                          setTitle(function (param) {
                                                return e.target.value;
                                              });
                                        })
                                    })
                              ],
                              className: "flex flex-col"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("label", {
                                      children: "Description:",
                                      className: "text-sm mb-1"
                                    }),
                                JsxRuntime.jsx("input", {
                                      className: "border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500",
                                      placeholder: "What's the description of your To Do?",
                                      value: description,
                                      onChange: (function (e) {
                                          setDescription(function (param) {
                                                return e.target.value;
                                              });
                                        })
                                    })
                              ],
                              className: "flex flex-col"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Add",
                              className: "p-2 bg-green-500 text-white rounded-md hover:bg-green-200",
                              type: "submit"
                            })
                      ],
                      className: "flex flex-col sm:flex-row items-end space-y-4 sm:space-y-0 sm:space-x-4",
                      onSubmit: (function (param) {
                          handleSubmit();
                        })
                    })
              ],
              className: "flex flex-col items-center p-4 bg-gray-900 text-white rounded-lg"
            });
}

var make = TaskInput;

export {
  make ,
}
/* react Not a pure module */
