// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TaskItem from "./TaskItem.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function TaskList(props) {
  var removeTask = props.removeTask;
  var completeTask = props.completeTask;
  return JsxRuntime.jsx("div", {
              children: props.tasks.map(function (task, index) {
                    return JsxRuntime.jsx(TaskItem.make, {
                                task: task,
                                completeTask: (function () {
                                    completeTask(index);
                                  }),
                                removeTask: (function () {
                                    removeTask(index);
                                  })
                              }, String(index));
                  }),
              className: "task-list"
            });
}

var make = TaskList;

export {
  make ,
}
/* TaskItem Not a pure module */
