// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function TaskInput(props) {
  var addTask = props.addTask;
  var match = React.useState(function () {
        return "";
      });
  var setTask = match[1];
  var task = match[0];
  var handleSubmit = function () {
    if (task !== "") {
      addTask(task);
      return setTask(function (prevTask) {
                  return "";
                });
    }
    
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Gestionnaire de tâches minimaliste",
                      className: "font-bold",
                      style: {
                        fontFamily: "Times New Roman",
                        fontSize: "15px"
                      }
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Liste de Tâches",
                      className: "text-xl ",
                      style: {
                        fontSize: "15px"
                      }
                    }),
                JsxRuntime.jsxs("form", {
                      children: [
                        JsxRuntime.jsx("input", {
                              className: "border border-gray-300 rounded-l-md p-2 flex-grow focus:outline-none focus:ring-2 focus:ring-blue-500",
                              placeholder: "Ajouter une nouvelle tâche...",
                              value: task,
                              onChange: (function (e) {
                                  setTask(function (param) {
                                        return e.target.value;
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Ajouter",
                              className: "ml-2 p-2 bg-blue-500 text-white rounded-md hover:bg-blue-600",
                              type: "submit"
                            })
                      ],
                      className: "task-input mt-4",
                      onSubmit: (function (param) {
                          handleSubmit();
                        })
                    })
              ],
              className: "flex flex-col items-center"
            });
}

var make = TaskInput;

export {
  make ,
}
/* react Not a pure module */
