// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TaskList from "../components/tasks/TaskList.res.mjs";
import * as TaskInput from "../components/tasks/TaskInput.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return [];
      });
  var setTasks = match[1];
  var addTask = function (newTask) {
    setTasks(function (tasks) {
          return Belt_Array.concatMany([
                      tasks,
                      [{
                          text: newTask,
                          isComplete: false
                        }]
                    ]);
        });
  };
  var completeTask = function (index) {
    setTasks(function (tasks) {
          return tasks.map(function (task, i) {
                      if (i === index) {
                        return {
                                text: task.text,
                                isComplete: !task.isComplete
                              };
                      } else {
                        return task;
                      }
                    });
        });
  };
  var removeTask = function (index) {
    setTasks(function (tasks) {
          return tasks.filter(function (param, i) {
                      return i !== index;
                    });
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(TaskInput.make, {
                      addTask: addTask
                    }),
                JsxRuntime.jsx(TaskList.make, {
                      tasks: match[0],
                      completeTask: completeTask,
                      removeTask: removeTask
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
