// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TaskList from "../components/tasks/TaskList.res.mjs";
import * as TaskInput from "../components/tasks/TaskInput.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Tasks(props) {
  var match = React.useState(function () {
        return [];
      });
  var setTasks = match[1];
  var addTask = function (title, description) {
    setTasks(function (tasks) {
          return Belt_Array.concatMany([
                      tasks,
                      [{
                          title: title,
                          description: description,
                          isComplete: false
                        }]
                    ]);
        });
  };
  var completeTask = function (index) {
    setTasks(function (tasks) {
          return tasks.map(function (task, i) {
                      if (i === index) {
                        return {
                                title: task.title,
                                description: task.description,
                                isComplete: !task.isComplete
                              };
                      } else {
                        return task;
                      }
                    });
        });
  };
  var removeTask = function (index) {
    setTasks(function (tasks) {
          return tasks.filter(function (param, i) {
                      return i !== index;
                    });
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("header", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Gestion des Tâches",
                              className: "text-lg font-bold"
                            }),
                        JsxRuntime.jsx("nav", {
                              children: JsxRuntime.jsxs("ul", {
                                    children: [
                                      JsxRuntime.jsx("li", {
                                            children: JsxRuntime.jsx("a", {
                                                  children: "Accueil",
                                                  className: "hover:underline",
                                                  href: "#"
                                                })
                                          }),
                                      JsxRuntime.jsx("li", {
                                            children: JsxRuntime.jsx("a", {
                                                  children: "À propos",
                                                  className: "hover:underline",
                                                  href: "#"
                                                })
                                          }),
                                      JsxRuntime.jsx("li", {
                                            children: JsxRuntime.jsx("a", {
                                                  children: "contact",
                                                  className: "hover:underline",
                                                  href: "#"
                                                })
                                          })
                                    ],
                                    className: "flex space-x-4"
                                  })
                            })
                      ],
                      className: "flex items-center justify-between p-4 bg-blue-500 text-white"
                    }),
                JsxRuntime.jsx("h1", {
                      children: "Liste de Tâches",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx(TaskInput.make, {
                      addTask: addTask
                    }),
                JsxRuntime.jsx(TaskList.make, {
                      tasks: match[0],
                      completeTask: completeTask,
                      removeTask: removeTask
                    })
              ],
              className: "p-6"
            });
}

var make = Tasks;

export {
  make ,
}
/* react Not a pure module */
