// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function TaskTable(props) {
  var onDelete = props.onDelete;
  var onModify = props.onModify;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("table", {
                    children: [
                      JsxRuntime.jsx("thead", {
                            children: JsxRuntime.jsxs("tr", {
                                  children: [
                                    JsxRuntime.jsx("th", {
                                          children: "ID",
                                          className: "py-2 px-4 border-b"
                                        }),
                                    JsxRuntime.jsx("th", {
                                          children: "Titre",
                                          className: "py-2 px-4 border-b"
                                        }),
                                    JsxRuntime.jsx("th", {
                                          children: "Description",
                                          className: "py-2 px-4 border-b"
                                        }),
                                    JsxRuntime.jsx("th", {
                                          children: "Actions",
                                          className: "py-2 px-4 border-b"
                                        })
                                  ]
                                })
                          }),
                      JsxRuntime.jsx("tbody", {
                            children: props.tasks.map(function (task) {
                                  return JsxRuntime.jsxs("tr", {
                                              children: [
                                                JsxRuntime.jsx("td", {
                                                      children: task.title,
                                                      className: "py-2 px-4 border-b"
                                                    }),
                                                JsxRuntime.jsx("td", {
                                                      children: task.description,
                                                      className: "py-2 px-4 border-b"
                                                    }),
                                                JsxRuntime.jsxs("td", {
                                                      children: [
                                                        JsxRuntime.jsx("button", {
                                                              children: "Modifier",
                                                              className: "bg-green-500 text-white px-4 py-2 rounded mr-2",
                                                              onClick: (function (param) {
                                                                  onModify(task);
                                                                })
                                                            }),
                                                        JsxRuntime.jsx("button", {
                                                              children: "Supprimer",
                                                              className: "bg-red-500 text-white px-4 py-2 rounded",
                                                              onClick: (function (param) {
                                                                  onDelete(task.id);
                                                                })
                                                            })
                                                      ],
                                                      className: "py-2 px-4 border-b"
                                                    })
                                              ]
                                            }, task.title);
                                })
                          })
                    ],
                    className: "min-w-full bg-white"
                  }),
              className: "container mx-auto mt-8"
            });
}

var make = TaskTable;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
