// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function HelloWorld(props) {
  return JsxRuntime.jsx("h1", {
              children: "Hello, " + props.name + "!"
            });
}

var make = HelloWorld;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
