// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Login from "./pages/Login.res.mjs";
import * as Tasks from "./pages/Tasks.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function App(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match && match.hd === "login" && !match.tl) {
    return JsxRuntime.jsx(Login.make, {});
  } else {
    return JsxRuntime.jsx(Tasks.make, {});
  }
}

var make = App;

export {
  make ,
}
/* Login Not a pure module */
